---
title: "Week 11 Functions"
author: "Sean Sutton"
date: '2022-10-28'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Setup

## Libraries
```{r}
library(tidyverse)
library(ggplot2)
library(MASS)
```

## Data
```{r}
air <- read.csv("dat/aircraft.csv")
air$Period = as.factor(air$Period)
head(air)
```

# Section 1

## Basic LDA prediction and plot
```{r}
# use the lda(formula, data=data) command to set up lda model
lda.0 = lda( Period ~ Power + Span + Length + Weight + Speed + Range, data = air )

# access the predicted class for each observation with $class
preds.0 = predict( lda.0 )$class

# compare the predictions to the true values
xtabs( ~ preds.0 + air$Period )

# plot the classes against a visual representation of distribution
plot( lda.0 )
```
```{r}
### create nicer plots of lda
plot_lda <- function(data, lda.scaling, class) {
  lda.df <- data.frame(cbind(as.matrix(data) %*% lda.scaling,as.factor(class)))
  ggplot(data=lda.df,  aes(x=LD1,y=LD2,col=class)) +
       geom_point()
}

plot_lda(air[,3:8], lda.0$scaling, air$Period)
```
## Adjusting lda proportions
```{r}
# to treat lda as if it has no proportions, set the priors parameters to sum to 1 and be equal for each variable
# this means the sizes of the groups won't be scaled
lda_even_prior = function(num_classes) {
  return(rep(1/num_classes, num_classes))
}
prior = lda_even_prior(3) # c(1/3, 1/3, 1/3)
lda.1 = lda( Period ~ Power + Span + Length + Weight + Speed + Range, data = air, prior = prior)
```

## QDA
```{r}
qda.0 = qda( Period ~ Power + Span + Length + Weight + Speed + Range, data = air)
qda.preds.0 = predict( qda.0 )$class
xtabs( ~ qda.preds.0 + air$Period )
```
## Fisher's LDA
```{r}
data = air[,3:8]
classes = air$Period
Ws = list()
mus = list()
for (class in unique(classes)) {
  data.subset = data[classes == class,]
  Ws[[class]] = cov(data.subset)
  mus[[class]] = colMeans(data.subset)
}
W = Reduce("+", Ws) # just takes the sum
mu = Reduce(rbind, mus)
B = ( 3 - 1 ) * cov (mu )
Q = solve(W, B)
eta = eigen(Q)$vectors[,1]

XX = data
XXproj = as.matrix( XX ) %*% as.matrix( eta )
muPs = list()
ms = list()
tXXproj = t( XXproj )
for (class in classes) {
  muPs[[class]] = t(as.matrix(mus[[class]])) %*% as.matrix(eta)
  ms[[class]] = as.data.frame(tXXproj) - muPs[[class]]
}

mm = abs(Reduce(rbind, ms))
assigned = sapply( mm, which.min )
classified = data.frame( assigned = assigned, true_classes = classes )
xtabs( ~ assigned + true_classes , data = classified)
```


```{r}
W1 = cov( dplyr::select( dplyr::filter( aircraft, Period == 1 ), -Year, -Period ) )
W2 = cov( dplyr::select( dplyr::filter( aircraft, Period == 2 ), -Year, -Period ) )
W3 = cov( dplyr::select( dplyr::filter( aircraft, Period == 3 ), -Year, -Period ) )
W = W1 + W2 + W3

mu1 = colMeans( dplyr::select( dplyr::filter( aircraft, Period == 1 ), -Year, -Period ) )
mu2 = colMeans( dplyr::select( dplyr::filter( aircraft, Period == 2 ), -Year, -Period ) )
mu3 = colMeans( dplyr::select( dplyr::filter( aircraft, Period == 3 ), -Year, -Period ) )
mu = rbind( mu1, mu2, mu3 )
B = ( 3 - 1 ) * cov (mu )

Q = solve(W, B)
eta = eigen(Q)$vectors[,1]
XX = dplyr::select( aircraft, -Year, -Period )
XXproj = as.matrix( XX ) %*% as.matrix( eta )
muP1 = t( as.matrix( mu1 ) ) %*% as.matrix( eta )
muP2 = t( as.matrix( mu2 ) ) %*% as.matrix( eta )
muP3 = t( as.matrix( mu3 ) ) %*% as.matrix( eta )
tXXproj = t( XXproj )
m1 = as.data.frame( tXXproj ) - muP1
m2 = as.data.frame( tXXproj ) - muP2
m3 = as.data.frame( tXXproj ) - muP3
mm = rbind( abs( m1 ), abs( m2 ), abs( m3 ) )
classes.2 = sapply( mm, which.min )
classified = data.frame( assigned = classes, aircraft )
xtabs( ~ assigned + Period , data = classified)
```


