---
title: "Week5_Functions_FA"
author: "Sean"
date: '2022-10-02'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Description & Libraries & Example Data

This notebook relates to week 5 lab 4, content from lecture 4 around factor analysis.

```{r}
library(ggplot2)
library(MASS)
library(tidyverse)
```

```{r}
aircraft_raw <- read.csv("dat/aircraft.csv")
wine_raw <- read.csv("dat/wine.tsv", header=FALSE)

air <- aircraft_raw %>%
  dplyr::select(3:8) %>%
  mutate_all(log10) %>% 
  mutate_all(scale)

wine <- wine_raw %>%
  dplyr::select(2:14) %>%
  mutate_all(scale)

head(air)
head(wine)
```

## PCFA Factor loadings

### Get the PCFA loadings

```{r}
PCFA_loadings = function(data, n_loadings){
  "Calculate the first n_loadings PCFA loadings"
  eig <- eigen(cov(data))
  vecs <- eig$vectors
  triangle <- diag(eig$values) ^ 0.5
  loadings <- vecs %*% triangle
  return(loadings[,1:n_loadings])
  
}

# e.g.
loadings.2 <- PCFA_loadings(air, 2)
loadings.2
```
### Get the varimax optimal loadings
```{r}
# just run varimax(loadings)
# note you will have to access your new loadings with $loadings and the rotation of the loadings with $rotmat
varimax(loadings.2)$loadings
```

```{r}
# if you only want the loadings for variables in an array further restrict with this with [1:n_vars,]
loadings.2.varimax <- varimax(loadings.2)$loadings[1:6,]
loadings.2.varimax
```
### Display these loadings
```{r}
# use biplot(loadings, loadings), e.g.
biplot(loadings.2, loadings.2)
biplot(loadings.2.varimax, loadings.2.varimax)
```
### sigma_hat_sq
```{r}
sigma_hat_sq = function(data, k){
  d = ncol(data)
  cov_mat = cov(data)
  eigen_vals = eigen(cov_mat)$values
  sigma_h_2 = (1 / (d-k)) * sum(eigen_vals[(k+1):d])
  return(sigma_h_2)
}

sigma_hat_sq(wine, 2)
```

## Principal Axis Factoring

Check below against assignment 2 answers
```{r}
data= wine
k=2
principal_axis_loadings <- function(data, k) {
  d=ncol(data)
  S = cov( data )
  Om = diag( rep( sigma_hat_sq(data, k), d ) )
  S_A = S - Om
  
  eig_A = eigen( S_A )
  Gamma_hat_2 = eig_A$vectors[ ,1:k]
  Lambda_hat_2 = diag( eig_A$values[1:k]^(1/2) )
  Ahat = Gamma_hat_2 %*% Lambda_hat_2
  return(Ahat)
}

principal_axis_loadings(wine, 2)
```


## ML factors

```{r}
# plan ML factor loadings
factanal( air, factors = 2, rotation = "none", scores = "regression" )

# varimax orthogonal
factanal( air, factors = 2, rotation = "varimax", scores = "regression" )

# varimax optimal oblique
factanal( air, factors = 2, rotation = "promax", scores = "regression" )
```

Convert below to function
```{r}
wine_tests_table = data.frame()
cultivar_tests_table = data.frame()
for (i in 1:8) {
  wine.factanal <- factanal(wine, i, rotation = "none")
  wine.row <- data.frame(k=i, DoF = wine.factanal$dof, Test_Statistic = wine.factanal$STATISTIC,
                         p_val = wine.factanal$PVAL)
  wine_tests_table = rbind(wine_tests_table, wine.row)
  
  cultivar.factanal <- factanal(cultivar12, i, rotation = "none")
  cultivar.row <- data.frame(k=i, DoF = cultivar.factanal$dof, Test_Statistic = cultivar.factanal$STATISTIC,
                         p_val = cultivar.factanal$PVAL)
  cultivar_tests_table = rbind(cultivar_tests_table, cultivar.row)
}
```